%% =========================================================================
%  STAGE 1 — Dataset Validation
%  Research: ML-Enhanced MPC for Wind Turbines (NREL 5-MW)
%
%  PURPOSE
%    Validates the dataset generated by stage1_generate_data before
%    any ML training. Checks:
%      1. Dataset dimensions and split counts
%      2. Operating space coverage (omega, beta, V, u)
%      3. Physical consistency (Cp bounds, omega bounds)
%      4. Target distribution (one-step increments)
%      5. Low-pass filter effect on wind signal
%      6. Trajectory structure integrity (for LSTM)
%      7. Normalisation statistics
%
%  PASS CRITERIA
%    - omega_max <= omega_max_limit
%    - Cp_max <= Betz limit
%    - beta in [0, 25] deg
%    - Train/val/test counts match expected fractions
%    - No NaN or Inf in X_in, X_out
%
%  PRODUCES
%    Fig1_S1_Coverage.png       operating space scatter plots
%    Fig1_S1_Increments.png     one-step delta distributions
%    Fig1_S1_Filter.png         LPF effect on wind signal
%    Fig1_S1_Split.png          train/val/test trajectory distribution
%
%  HOW TO RUN
%    cfg  = stage0_config();
%    data = stage1_generate_data(cfg);
%    stage1_validate(data);
%    % or: load stage1_data.mat; stage1_validate(data)
% =========================================================================

function stage1_validate(data)

if nargin < 1
    if ~exist('stage1_data.mat','file')
        error('stage1_data.mat not found. Run stage1_generate_data first.');
    end
    data = load('stage1_data.mat');
end

fprintf('==========================================\n');
fprintf('  STAGE 1: Dataset Validation\n');
fprintf('==========================================\n\n');

X_in  = data.X_in;
X_out = data.X_out;
info  = data.info;
norm  = data.norm;
p     = data.p;
cfg   = data.cfg;

idx_tr = data.idx_train;
idx_va = data.idx_val;
idx_te = data.idx_test;

BETZ  = 16/27;
FMT   = cfg.export.fmt;
RES   = cfg.export.res;

C1 = [0.22 0.55 0.95];
C2 = [0.17 0.76 0.43];
C3 = [0.96 0.38 0.18];
CGRAY = [0.6 0.6 0.6];

%% ── TEST 1: Dimensions and split ─────────────────────────────────────────────
fprintf('[1/7] Dataset dimensions...\n');
[N, nfeat] = size(X_in);
[~, nout]  = size(X_out);

pass1a = N == info.N_traj * info.N_steps;
pass1b = nfeat == 4;
pass1c = nout  == 2;
pass1d = numel(idx_tr) + numel(idx_va) + numel(idx_te) == N;

expected_tr = floor(cfg.data.frac_train * info.N_traj) * info.N_steps;
expected_va = floor(cfg.data.frac_val   * info.N_traj) * info.N_steps;
pass1e = numel(idx_tr) == expected_tr;
pass1f = numel(idx_va) == expected_va;

fprintf('  Total samples  : %d  (expected %d)  → %s\n', N, info.N_traj*info.N_steps, tf(pass1a));
fprintf('  Features       : %d  (expected 4)   → %s\n', nfeat, tf(pass1b));
fprintf('  Targets        : %d  (expected 2)   → %s\n', nout,  tf(pass1c));
fprintf('  Split sum = N  : %s\n', tf(pass1d));
fprintf('  Train count    : %d  (expected %d)  → %s\n', numel(idx_tr), expected_tr, tf(pass1e));
fprintf('  Val   count    : %d  (expected %d)  → %s\n', numel(idx_va), expected_va, tf(pass1f));

%% ── TEST 2: NaN / Inf check ──────────────────────────────────────────────────
fprintf('[2/7] NaN/Inf check...\n');
pass2a = ~any(isnan(X_in(:))) && ~any(isinf(X_in(:)));
pass2b = ~any(isnan(X_out(:))) && ~any(isinf(X_out(:)));
fprintf('  X_in  clean : %s\n', tf(pass2a));
fprintf('  X_out clean : %s\n', tf(pass2b));

%% ── TEST 3: Physical bounds ──────────────────────────────────────────────────
fprintf('[3/7] Physical bounds...\n');
omega_min_data = min(X_in(:,1)) * 30/pi;
omega_max_data = max(X_in(:,1)) * 30/pi;
beta_min_data  = min(X_in(:,2));
beta_max_data  = max(X_in(:,2));
V_min_data     = min(X_in(:,3));
V_max_data     = max(X_in(:,3));

pass3a = omega_max_data <= p.omega_max * 30/pi + 0.1;
pass3b = beta_min_data  >= p.beta_cp_min - 0.1;
pass3c = beta_max_data  <= p.beta_cp_max + 0.1;
pass3d = V_min_data     >= 3.0 - 0.1;
pass3e = info.Cp_max_data <= BETZ + 1e-4;

fprintf('  omega_max = %.2f rpm  (limit %.2f)  → %s\n', omega_max_data, p.omega_max*30/pi, tf(pass3a));
fprintf('  beta in [%.1f, %.1f] deg             → %s / %s\n', beta_min_data, beta_max_data, tf(pass3b), tf(pass3c));
fprintf('  V_min     = %.2f m/s  (cut-in 3.0)  → %s\n', V_min_data, tf(pass3d));
fprintf('  Cp_max    = %.4f  (Betz %.4f)       → %s\n', info.Cp_max_data, BETZ, tf(pass3e));

%% ── TEST 4: Trajectory structure (LSTM integrity) ────────────────────────────
fprintf('[4/7] Trajectory structure...\n');
% Check that each trajectory appears as a contiguous block of N_steps rows
traj_id = data.traj_id;
pass4 = true;
for k = 1:info.N_traj
    rows_k = find(traj_id == k);
    if numel(rows_k) ~= info.N_steps
        pass4 = false;
        fprintf('  WARNING: trajectory %d has %d rows (expected %d)\n', ...
                k, numel(rows_k), info.N_steps);
    end
end
fprintf('  All trajectories have %d steps  → %s\n', info.N_steps, tf(pass4));

% Check train/val/test trajectories are disjoint
overlap_trva = intersect(info.traj_tr, info.traj_val);
overlap_trte = intersect(info.traj_tr, info.traj_te);
overlap_vate = intersect(info.traj_val, info.traj_te);
pass4b = isempty(overlap_trva) && isempty(overlap_trte) && isempty(overlap_vate);
fprintf('  Splits are disjoint                → %s\n', tf(pass4b));

%% ── TEST 5: One-step increment distribution ──────────────────────────────────
fprintf('[5/7] One-step increments...\n');
delta_omega = (X_out(:,1) - X_in(:,1)) * 30/pi;   % [rpm]
delta_beta  = X_out(:,2) - X_in(:,2);              % [deg]

fprintf('  delta_omega: mean=%.4f  std=%.4f  max=%.4f rpm\n', ...
        mean(delta_omega), std(delta_omega), max(abs(delta_omega)));
fprintf('  delta_beta : mean=%.4f  std=%.4f  max=%.4f deg\n', ...
        mean(delta_beta),  std(delta_beta),  max(abs(delta_beta)));

% Large increments would indicate numerical instability
pass5 = max(abs(delta_omega)) < 5.0 && max(abs(delta_beta)) < p.dbeta_max * cfg.data.dt * 2;
fprintf('  Increments within physical limits  → %s\n', tf(pass5));

%% ── TEST 6: Normalisation statistics ─────────────────────────────────────────
fprintf('[6/7] Normalisation...\n');
X_tr_n = (X_in(idx_tr,:) - norm.xmu) ./ norm.xsig;
pass6a = abs(mean(X_tr_n(:,1))) < 0.01;
pass6b = abs(std(X_tr_n(:,1))  - 1.0) < 0.01;
fprintf('  Normalised omega train: mean=%.4f  std=%.4f  → %s\n', ...
        mean(X_tr_n(:,1)), std(X_tr_n(:,1)), tf(pass6a && pass6b));

%% ── FIG 1: Operating space coverage ──────────────────────────────────────────
fprintf('[7/7] Generating figures...\n');

f1 = figure('Color','w','Position',[40 40 1100 480]);
subplot(1,3,1)
scatter(X_in(idx_tr,3), X_in(idx_tr,1)*30/pi, 2, C1, 'filled', ...
        'MarkerFaceAlpha',0.2,'DisplayName','Train');
hold on
scatter(X_in(idx_te,3), X_in(idx_te,1)*30/pi, 2, C3, 'filled', ...
        'MarkerFaceAlpha',0.4,'DisplayName','Test');
yline(p.omega_r*30/pi,'k--','omega rated','FontSize',8);
xlabel('V_{wind} [m/s]','FontSize',11); ylabel('\omega_r [rpm]','FontSize',11);
title('Speed vs Wind Speed','FontSize',11,'FontWeight','bold');
legend('FontSize',9); grid on; set(gca,'FontSize',9);

subplot(1,3,2)
scatter(X_in(idx_tr,3), X_in(idx_tr,2), 2, C1, 'filled','MarkerFaceAlpha',0.2);
hold on
scatter(X_in(idx_te,3), X_in(idx_te,2), 2, C3, 'filled','MarkerFaceAlpha',0.4);
xlabel('V_{wind} [m/s]','FontSize',11); ylabel('\beta [deg]','FontSize',11);
title('Pitch vs Wind Speed','FontSize',11,'FontWeight','bold');
grid on; set(gca,'FontSize',9);

subplot(1,3,3)
scatter(X_in(idx_tr,4), X_in(idx_tr,2), 2, C1, 'filled','MarkerFaceAlpha',0.2);
hold on
scatter(X_in(idx_te,4), X_in(idx_te,2), 2, C3, 'filled','MarkerFaceAlpha',0.4);
xlabel('u_{cmd} [deg]','FontSize',11); ylabel('\beta [deg]','FontSize',11);
title('Pitch vs Command','FontSize',11,'FontWeight','bold');
grid on; set(gca,'FontSize',9);

sgtitle('Stage 1 — Operating Space Coverage (Train vs Test)', ...
        'FontSize',12,'FontWeight','bold');
print(f1,'Fig1_S1_Coverage',FMT,RES);

%% ── FIG 2: One-step increment distributions ──────────────────────────────────
f2 = figure('Color','w','Position',[40 40 900 420]);
subplot(1,2,1)
histogram(delta_omega(idx_tr), 80, 'FaceColor',C1, 'EdgeColor','none', ...
          'Normalization','pdf');
xlabel('\Delta\omega_r [rpm]','FontSize',11);
ylabel('PDF','FontSize',11);
title('One-step rotor speed increment','FontSize',11,'FontWeight','bold');
grid on; set(gca,'FontSize',10);

subplot(1,2,2)
histogram(delta_beta(idx_tr), 80, 'FaceColor',C2, 'EdgeColor','none', ...
          'Normalization','pdf');
xlabel('\Delta\beta [deg]','FontSize',11);
ylabel('PDF','FontSize',11);
title('One-step pitch increment','FontSize',11,'FontWeight','bold');
grid on; set(gca,'FontSize',10);

sgtitle('Stage 1 — One-step Target Distributions (Training Set)', ...
        'FontSize',12,'FontWeight','bold');
print(f2,'Fig1_S1_Increments',FMT,RES);

%% ── FIG 3: LPF effect ────────────────────────────────────────────────────────
% Show one example trajectory with and without filter
if cfg.data.apply_lpf
    dc = cfg.data;
    Wn = dc.lpf_cutoff / (0.5/dc.dt);
    [b_lpf, a_lpf] = butter(dc.lpf_order, Wn, 'low');
    V_raw = kaimal_wind(14, dc.T_traj, dc.dt, 100);
    V_filt = filtfilt(b_lpf, a_lpf, V_raw);
    t_ex = (0:dc.N_steps-1)' * dc.dt;

    f3 = figure('Color','w','Position',[40 40 1000 420]);
    subplot(1,2,1)
    plot(t_ex, V_raw,  '-','Color',CGRAY,'LineWidth',0.8,'DisplayName','Raw Kaimal');
    hold on
    plot(t_ex, V_filt, '-','Color',C3,   'LineWidth',1.8,'DisplayName', ...
         sprintf('LPF (fc=%.1f Hz, order %d)', dc.lpf_cutoff, dc.lpf_order));
    xlabel('Time [s]','FontSize',11); ylabel('V_{wind} [m/s]','FontSize',11);
    title('Wind Signal — Raw vs Filtered','FontSize',11,'FontWeight','bold');
    legend('FontSize',10); grid on; set(gca,'FontSize',10);

    subplot(1,2,2)
    N_ex   = dc.N_steps;
    df_ex  = 1/(N_ex*dc.dt);
    f_ex   = (1:floor(N_ex/2))' * df_ex;
    Praw   = 2*abs(fft(V_raw  - mean(V_raw))).^2  / (N_ex * df_ex);
    Pfilt  = 2*abs(fft(V_filt - mean(V_filt))).^2 / (N_ex * df_ex);
    loglog(f_ex, Praw(2:floor(N_ex/2)+1),  '-','Color',CGRAY,'LineWidth',0.8,...
           'DisplayName','Raw');
    hold on
    loglog(f_ex, Pfilt(2:floor(N_ex/2)+1), '-','Color',C3,'LineWidth',1.8,...
           'DisplayName','Filtered');
    xline(dc.lpf_cutoff,'k--',sprintf('f_c = %.1f Hz',dc.lpf_cutoff),'FontSize',9);
    xlabel('Frequency [Hz]','FontSize',11);
    ylabel('PSD [m^2/s]','FontSize',11);
    title('PSD — Raw vs Filtered','FontSize',11,'FontWeight','bold');
    legend('FontSize',10); grid on; set(gca,'FontSize',10);

    sgtitle(sprintf('Stage 1 — Low-Pass Filter Effect (fc = %.1f Hz, order %d)', ...
            dc.lpf_cutoff, dc.lpf_order), 'FontSize',12,'FontWeight','bold');
    print(f3,'Fig1_S1_Filter',FMT,RES);
end

%% ── FIG 4: Split distribution ────────────────────────────────────────────────
f4 = figure('Color','w','Position',[40 40 900 380]);
traj_V = zeros(info.N_traj, 1);
for k = 1:info.N_traj
    rows_k = find(data.traj_id == k);
    traj_V(k) = mean(X_in(rows_k, 3));
end

hold on
scatter(info.traj_tr,  traj_V(info.traj_tr),  40, C1, 'filled','DisplayName','Train');
scatter(info.traj_val, traj_V(info.traj_val),  40, C2, 'filled','DisplayName','Val');
scatter(info.traj_te,  traj_V(info.traj_te),   60, C3, 'filled','DisplayName','Test');
xlabel('Trajectory index','FontSize',11);
ylabel('Mean V_{wind} [m/s]','FontSize',11);
title('Train / Val / Test Split by Trajectory', ...
      'FontSize',12,'FontWeight','bold');
legend('Location','best','FontSize',10);
grid on; set(gca,'FontSize',10);
print(f4,'Fig1_S1_Split',FMT,RES);

%% ── Summary ──────────────────────────────────────────────────────────────────
all_pass = pass1a && pass1b && pass1c && pass1d && pass1e && pass1f ...
        && pass2a && pass2b && pass3a && pass3b && pass3c && pass3d ...
        && pass3e && pass4  && pass4b && pass5  && pass6a && pass6b;

fprintf('\n==========================================\n');
fprintf('  STAGE 1 VALIDATION SUMMARY\n');
fprintf('==========================================\n');
fprintf('  Dimensions correct    : %s\n', tf(pass1a&&pass1b&&pass1c&&pass1d));
fprintf('  Split counts correct  : %s\n', tf(pass1e&&pass1f));
fprintf('  No NaN/Inf            : %s\n', tf(pass2a&&pass2b));
fprintf('  omega within limits   : %s\n', tf(pass3a));
fprintf('  beta within domain    : %s\n', tf(pass3b&&pass3c));
fprintf('  Cp <= Betz            : %s\n', tf(pass3e));
fprintf('  Trajectory structure  : %s\n', tf(pass4&&pass4b));
fprintf('  Increments physical   : %s\n', tf(pass5));
fprintf('  Normalisation correct : %s\n', tf(pass6a&&pass6b));
fprintf('------------------------------------------\n');
if all_pass
    fprintf('  ALL TESTS PASSED — ready for Stage 2\n');
else
    fprintf('  WARNING: some tests failed — review above\n');
end
fprintf('==========================================\n\n');

fprintf('  Dataset summary:\n');
fprintf('  Total samples : %d\n',       info.N_total);
fprintf('  Train         : %d  (%d traj)\n', numel(idx_tr), info.n_tr);
fprintf('  Val           : %d  (%d traj)\n', numel(idx_va), info.n_val);
fprintf('  Test          : %d  (%d traj)\n', numel(idx_te), info.n_te);
fprintf('  omega range   : %.2f – %.2f rpm\n', info.omega_range);
fprintf('  beta  range   : %.2f – %.2f deg\n', info.beta_range);
fprintf('  V     range   : %.2f – %.2f m/s\n', info.V_range);
fprintf('  Cp_max        : %.4f  (Betz = %.4f)\n', info.Cp_max_data, BETZ);

%% ── Write results/stage1_validate_results.txt [ADDED] ───────────────────────
if ~exist('results', 'dir'), mkdir('results'); end
fid = fopen(fullfile('results','stage1_validate_results.txt'), 'w');
fprintf(fid, 'STAGE 1 DATASET VALIDATION RESULTS\n');
fprintf(fid, 'Generated: %s\n', datestr(now));
fprintf(fid, '================================================\n\n');
fprintf(fid, 'total_samples = %d\n', info.N_total);
fprintf(fid, 'train_samples = %d\n', numel(idx_tr));
fprintf(fid, 'val_samples = %d\n', numel(idx_va));
fprintf(fid, 'test_samples = %d\n', numel(idx_te));
fprintf(fid, 'omega_range_rpm = [%.4f, %.4f]\n', info.omega_range);
fprintf(fid, 'beta_range_deg = [%.4f, %.4f]\n', info.beta_range);
fprintf(fid, 'V_range_ms = [%.4f, %.4f]\n', info.V_range);
fprintf(fid, 'Cp_max_data = %.6f\n', info.Cp_max_data);
fprintf(fid, 'pass_dimensions = %d\n', pass1a&&pass1b&&pass1c&&pass1d);
fprintf(fid, 'pass_split_counts = %d\n', pass1e&&pass1f);
fprintf(fid, 'pass_no_nan_inf = %d\n', pass2a&&pass2b);
fprintf(fid, 'pass_omega_limits = %d\n', pass3a);
fprintf(fid, 'pass_beta_domain = %d\n', pass3b&&pass3c);
fprintf(fid, 'pass_cp_betz = %d\n', pass3e);
fprintf(fid, 'pass_trajectory_structure = %d\n', pass4&&pass4b);
fprintf(fid, 'pass_increments_physical = %d\n', pass5);
fprintf(fid, 'pass_normalisation = %d\n', pass6a&&pass6b);
fprintf(fid, 'ALL_PASS = %d\n', all_pass);
fclose(fid);
fprintf('\nWrote results/stage1_validate_results.txt\n');

end

function s = tf(flag)
    if flag, s = 'PASS'; else, s = 'FAIL'; end
end
